# Generated by Django 4.0.3 on 2022-03-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
