# Generated by Django 4.0.3 on 2022-03-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
